---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.x-k8s.io
  resources:
  - jobsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.x-k8s.io
  resources:
  - jobsets/finalizers
  verbs:
  - update
- apiGroups:
  - batch.x-k8s.io
  resources:
  - jobsets/status
  verbs:
  - get
  - patch
  - update
